"""add new_email column to tokens

Revision ID: 710442dad2c4
Revises: 0a911e311bae
Create Date: 2026-04-08 20:42:19.931491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '710442dad2c4'
down_revision: Union[str, Sequence[str], None] = '0a911e311bae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('new_email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'new_email')
    # ### end Alembic commands ###
